from __future__ import annotations

import sys
from pathlib import Path

_src_dir = str(Path(__file__).parent.parent / "src")
if _src_dir not in sys.path:
	sys.path.insert(0, _src_dir)

from tests import test_pipeline as pipeline_tests

def test_stage3_summary_preserves_llm_timing_metadata(tmp_path, monkeypatch):
	pipeline_tests.assert_stage3_summary_preserves_llm_timing_metadata(tmp_path, monkeypatch)


def test_pipeline_requires_explicit_domain_file():
	pipeline_tests.assert_pipeline_requires_explicit_domain_file()


def test_seed_validation_scope_preserves_multi_type_object_assignments(tmp_path):
	pipeline_tests.assert_seed_validation_scope_preserves_multi_type_object_assignments(tmp_path)


def test_seed_validation_scope_accepts_parent_type_when_leaf_type_is_unconstrained(tmp_path):
	pipeline_tests.assert_seed_validation_scope_accepts_parent_type_when_leaf_type_is_unconstrained(
		tmp_path,
	)


def test_stage3_type_validation_fails_for_untyped_method_variable(tmp_path):
	pipeline_tests.assert_stage3_type_validation_fails_for_untyped_method_variable(tmp_path)


def test_problem_domain_name_mismatch_allows_compatible_problem(tmp_path):
	pipeline_tests.assert_problem_domain_name_mismatch_allows_compatible_problem(tmp_path)


def test_problem_domain_name_mismatch_rejects_incompatible_problem(tmp_path):
	pipeline_tests.assert_problem_domain_name_mismatch_rejects_incompatible_problem(tmp_path)


def test_method_task_argument_type_hints_prefer_explicit_task_args(tmp_path):
	pipeline_tests.assert_method_task_argument_type_hints_prefer_explicit_task_args(tmp_path)


def test_stage1_object_universe_merges_constants_from_atoms_and_formulas():
	pipeline_tests.assert_stage1_object_universe_merges_constants_from_atoms_and_formulas()


def test_ordered_literal_signatures_extracts_eventually_wrapped_atoms():
	pipeline_tests.assert_ordered_literal_signatures_extracts_eventually_wrapped_atoms()


def test_stage1_task_grounded_eventual_targets_drop_support_only_literals():
	pipeline_tests.assert_stage1_task_grounded_eventual_targets_drop_support_only_literals()


def test_stage1_task_grounded_singleton_support_targets_canonicalize_to_headline():
	pipeline_tests.assert_stage1_task_grounded_singleton_support_targets_canonicalize_to_headline()


def test_stage1_task_grounded_joint_eventual_bundle_canonicalizes_per_anchor():
	pipeline_tests.assert_stage1_task_grounded_joint_eventual_bundle_canonicalizes_per_anchor()


def test_stage1_task_grounded_satellite_headline_prefers_task_signature_match():
	pipeline_tests.assert_stage1_task_grounded_satellite_headline_prefers_task_signature_match()


def test_stage1_task_grounded_satellite_variable_arguments_use_typed_witness_grounding():
	pipeline_tests.assert_stage1_task_grounded_satellite_variable_arguments_use_typed_witness_grounding()


def test_stage1_task_grounded_objects_prefer_query_inventory_over_placeholder_tokens():
	pipeline_tests.assert_stage1_task_grounded_objects_prefer_query_inventory_over_placeholder_tokens()


def test_ipc_plan_verifier_grounds_parameterised_root_tasks_from_trace():
	pipeline_tests.assert_ipc_plan_verifier_grounds_parameterised_root_tasks_from_trace()


def test_ipc_plan_verifier_reconstructs_multi_root_depth_first_method_traces():
	pipeline_tests.assert_ipc_plan_verifier_reconstructs_multi_root_depth_first_method_traces()


def test_official_blocksworld_problem_query_case_generation_from_problem_tasks():
	pipeline_tests.assert_official_blocksworld_problem_query_case_generation_from_problem_tasks()


def test_official_blocksworld_problem_query_case_generation_preserves_identical_root_task_occurrences():
	pipeline_tests.assert_official_blocksworld_problem_query_case_generation_preserves_identical_root_task_occurrences()


def test_official_stage3_mask_infers_blocksworld_internal_task_headlines_generically():
	pipeline_tests.assert_official_stage3_mask_infers_blocksworld_internal_task_headlines_generically()


def test_official_stage3_mask_oracle_targets_fall_back_to_primary_task_effects():
	method_library = pipeline_tests._official_domain_method_library(
		"blocksworld",
		target_literal_signatures=[],
		query_task_anchors=[{"task_name": "do_put_on", "args": ["b1", "b2"]}],
	)
	assert [literal.to_signature() for literal in method_library.target_literals] == ["on(b1, b2)"]
	assert [binding.to_dict() for binding in method_library.target_task_bindings] == [
		{"target_literal": "on(b1, b2)", "task_name": "do_put_on"},
	]

	method_library = pipeline_tests._official_domain_method_library(
		"marsrover",
		target_literal_signatures=[],
		query_task_anchors=[{"task_name": "get_soil_data", "args": ["waypoint2"]}],
	)
	assert [literal.to_signature() for literal in method_library.target_literals] == [
		"communicated_soil_data(waypoint2)",
	]
	assert [binding.to_dict() for binding in method_library.target_task_bindings] == [
		{"target_literal": "communicated_soil_data(waypoint2)", "task_name": "get_soil_data"},
	]


def test_official_marsrover_problem_query_case_generation_from_problem_tasks():
	pipeline_tests.assert_official_marsrover_problem_query_case_generation_from_problem_tasks()


def test_stage6_guided_execution_uses_query_task_anchors_not_problem_root_tasks():
	pipeline_tests.assert_stage6_guided_execution_uses_query_task_anchors_not_problem_root_tasks()


def test_stage6_incremental_guided_execution_reuses_stage4_plan_record_when_task_plan_is_empty():
	pipeline_tests.assert_stage6_incremental_guided_execution_reuses_stage4_plan_record_when_task_plan_is_empty()


def test_stage6_query_task_network_grounds_parameterised_query_anchors_from_literal_contract():
	pipeline_tests.assert_stage6_query_task_network_grounds_parameterised_query_anchors_from_literal_contract()


def test_stage3_mask_transition_extraction_compat_supports_legacy_delegate_signature():
	pipeline_tests.assert_stage3_mask_transition_extraction_compat_supports_legacy_delegate_signature()


def test_stage3_transition_extraction_respects_unordered_query_semantics(tmp_path, monkeypatch):
	pipeline_tests.assert_stage3_transition_extraction_respects_unordered_query_semantics(
		tmp_path,
		monkeypatch,
	)


def test_stage6_guided_execution_falls_back_to_chunked_query_tasks_before_incremental():
	pipeline_tests.assert_stage6_guided_execution_falls_back_to_chunked_query_tasks_before_incremental()


def test_stage6_unordered_guided_execution_falls_back_to_chunked_query_tasks():
	pipeline_tests.assert_stage6_unordered_guided_execution_falls_back_to_chunked_query_tasks()


def test_stage6_chunked_guided_execution_caps_chunk_horizon_generically():
	pipeline_tests.assert_stage6_chunked_guided_execution_caps_chunk_horizon_generically()


def test_stage6_chunked_guided_execution_uses_longer_timeout_for_singleton_unordered_chunks():
	pipeline_tests.assert_stage6_chunked_guided_execution_uses_longer_timeout_for_singleton_unordered_chunks()


def test_stage6_chunked_guided_execution_retains_reduced_chunk_ceiling_after_failures():
	pipeline_tests.assert_stage6_chunked_guided_execution_retains_reduced_chunk_ceiling_after_failures()


def test_stage6_chunked_guided_execution_reorders_unordered_singleton_fallbacks_generically():
	pipeline_tests.assert_stage6_chunked_guided_execution_reorders_unordered_singleton_fallbacks_generically()


def test_stage6_chunked_guided_execution_preserves_hddl_fact_spellings_after_replay():
	pipeline_tests.assert_stage6_chunked_guided_execution_preserves_hddl_fact_spellings_after_replay()


def test_stage6_chunked_guided_execution_retries_task_network_when_goal_guided_chunk_is_empty():
	pipeline_tests.assert_stage6_chunked_guided_execution_retries_task_network_when_goal_guided_chunk_is_empty()


def test_stage6_chunked_guided_execution_retries_task_network_when_singleton_goal_guided_chunk_raises():
	pipeline_tests.assert_stage6_chunked_guided_execution_retries_task_network_when_singleton_goal_guided_chunk_raises()


def test_stage6_chunked_guided_execution_splits_large_empty_goal_guided_chunks_before_task_network_fallback():
	pipeline_tests.assert_stage6_chunked_guided_execution_splits_large_empty_goal_guided_chunks_before_task_network_fallback()


def test_stage6_chunked_guided_execution_preserves_partial_prefix_when_later_chunk_fails():
	pipeline_tests.assert_stage6_chunked_guided_execution_preserves_partial_prefix_when_later_chunk_fails()


def test_stage6_chunked_guided_execution_replans_small_tail_window_before_returning_partial():
	pipeline_tests.assert_stage6_chunked_guided_execution_replans_small_tail_window_before_returning_partial()


def test_stage6_unordered_guided_execution_probes_medium_reordered_network_before_chunking():
	pipeline_tests.assert_stage6_unordered_guided_execution_probes_medium_reordered_network_before_chunking()


def test_stage6_query_goal_projection_drops_transient_ordered_support_effects():
	pipeline_tests.assert_stage6_query_goal_projection_drops_transient_ordered_support_effects()


def test_stage6_chunked_hierarchical_plan_merge_preserves_structure():
	pipeline_tests.assert_stage6_chunked_hierarchical_plan_merge_preserves_structure()


def test_stage6_chunked_hierarchical_plan_merge_ignores_empty_root_only_chunks():
	pipeline_tests.assert_stage6_chunked_hierarchical_plan_merge_ignores_empty_root_only_chunks()


def test_stage7_prefers_guided_hierarchical_plan_text():
	pipeline_tests.assert_stage7_prefers_guided_hierarchical_plan_text()


def test_stage6_unordered_ordering_fallback_does_not_write_to_repo_root(monkeypatch):
	pipeline_tests.assert_stage6_unordered_ordering_fallback_does_not_write_to_repo_root(
		monkeypatch,
	)


def test_official_satellite_problem_query_case_generation_from_problem_tasks():
	pipeline_tests.assert_official_satellite_problem_query_case_generation_from_problem_tasks()


def test_benchmark_query_generation_uses_only_query_referenced_objects_when_grounded():
	pipeline_tests.assert_benchmark_query_generation_uses_only_query_referenced_objects_when_grounded()


def test_benchmark_query_dataset_matches_canonical_problem_generation():
	pipeline_tests.assert_benchmark_query_dataset_matches_canonical_problem_generation()


def test_benchmark_query_dataset_metadata_points_to_query_protocol():
	pipeline_tests.assert_benchmark_query_dataset_metadata_points_to_query_protocol()


def test_benchmark_query_dataset_cases_store_only_natural_language_inputs():
	pipeline_tests.assert_benchmark_query_dataset_cases_store_only_natural_language_inputs()


def test_benchmark_query_dataset_instructions_respect_protocol():
	pipeline_tests.assert_benchmark_query_dataset_instructions_respect_protocol()


def test_query_task_anchor_extraction_uses_declared_tasks_only():
	pipeline_tests.assert_query_task_anchor_extraction_uses_declared_tasks_only()


def test_ordered_literal_signatures_preserve_identical_occurrences():
	pipeline_tests.assert_ordered_literal_signatures_preserve_identical_occurrences()


def test_task_grounded_canonical_formulas_preserve_identical_obligation_occurrences():
	pipeline_tests.assert_task_grounded_canonical_formulas_preserve_identical_obligation_occurrences()


def test_task_grounded_stage1_normalisation_marks_default_queries_as_unordered():
	pipeline_tests.assert_task_grounded_stage1_normalisation_marks_default_queries_as_unordered()


def test_task_grounded_canonical_formulas_preserve_order_when_query_requests_sequence():
	pipeline_tests.assert_task_grounded_canonical_formulas_preserve_order_when_query_requests_sequence()


def test_task_grounded_stage1_normalisation_overrides_independent_eventuals_for_ordered_queries():
	pipeline_tests.assert_task_grounded_stage1_normalisation_overrides_independent_eventuals_for_ordered_queries()


def test_task_grounded_ordered_formulas_encode_sequential_task_events():
	pipeline_tests.assert_task_grounded_ordered_formulas_encode_sequential_task_events()


def test_ordered_literal_signatures_prefer_query_task_literal_contract():
	pipeline_tests.assert_ordered_literal_signatures_prefer_query_task_literal_contract()


def test_query_object_inventory_extraction_uses_minimal_query_referenced_inventory():
	pipeline_tests.assert_query_object_inventory_extraction_uses_minimal_query_referenced_inventory()


def test_expected_execution_identity_is_derived_from_selected_domain_and_problem():
	pipeline_tests.assert_expected_execution_identity_is_derived_from_selected_domain_and_problem()


def test_stage1_generation_uses_only_instruction_even_with_problem_file(monkeypatch):
	pipeline_tests.assert_stage1_generation_uses_only_instruction_even_with_problem_file(monkeypatch)


def test_oracle_task_grounded_stage1_mask_builds_canonical_blocksworld_spec():
	pipeline_tests.assert_oracle_task_grounded_stage1_mask_builds_canonical_blocksworld_spec()


def test_oracle_task_grounded_stage1_mask_grounds_parameterised_satellite_queries():
	pipeline_tests.assert_oracle_task_grounded_stage1_mask_grounds_parameterised_satellite_queries()


def test_pipeline_logger_stage1_payload_omits_recursive_formula_tree(tmp_path):
	pipeline_tests.assert_pipeline_logger_stage1_payload_omits_recursive_formula_tree(tmp_path)


def test_pipeline_logger_stage2_payload_omits_embedded_dfa_bodies(tmp_path):
	pipeline_tests.assert_pipeline_logger_stage2_payload_omits_embedded_dfa_bodies(tmp_path)


def test_pipeline_logger_stage4_payload_omits_embedded_transition_dump(tmp_path):
	pipeline_tests.assert_pipeline_logger_stage4_payload_omits_embedded_transition_dump(tmp_path)


def test_pipeline_logger_stage3_payload_records_only_artifact_path(tmp_path):
	pipeline_tests.assert_pipeline_logger_stage3_payload_records_only_artifact_path(tmp_path)


def test_pipeline_logger_stage5_payload_records_only_artifact_path(tmp_path):
	pipeline_tests.assert_pipeline_logger_stage5_payload_records_only_artifact_path(tmp_path)


def test_pipeline_logger_stage6_payload_records_relative_artifact_paths(tmp_path):
	pipeline_tests.assert_pipeline_logger_stage6_payload_records_relative_artifact_paths(tmp_path)


def test_pipeline_logger_stage7_payload_records_relative_artifact_paths(tmp_path):
	pipeline_tests.assert_pipeline_logger_stage7_payload_records_relative_artifact_paths(tmp_path)


def test_stage6_object_type_resolution_ignores_unused_query_objects():
	pipeline_tests.assert_stage6_object_type_resolution_ignores_unused_query_objects()


def test_stage6_object_type_resolution_preserves_problem_typed_runtime_symbols():
	pipeline_tests.assert_stage6_object_type_resolution_preserves_problem_typed_runtime_symbols()


def test_stage3_uses_query_inventory_for_grounding_even_when_semantic_objects_are_partial(
	tmp_path,
	monkeypatch,
):
	pipeline_tests.assert_stage3_uses_query_inventory_for_grounding_even_when_semantic_objects_are_partial(
		tmp_path,
		monkeypatch,
	)


def test_stage6_problem_seed_facts_ignore_stage4_witness_facts():
	pipeline_tests.assert_stage6_problem_seed_facts_ignore_stage4_witness_facts()


def test_method_validation_initial_facts_are_branch_specific(tmp_path):
	pipeline_tests.assert_method_validation_initial_facts_are_branch_specific(tmp_path)


def test_method_validation_initial_facts_avoid_conflicting_global_defaults(tmp_path):
	pipeline_tests.assert_method_validation_initial_facts_avoid_conflicting_global_defaults(tmp_path)


def test_task_witness_initial_facts_merge_sibling_branches(tmp_path):
	pipeline_tests.assert_task_witness_initial_facts_merge_sibling_branches(tmp_path)


def test_transition_witness_initial_facts_exclude_positive_target_literal(tmp_path):
	pipeline_tests.assert_transition_witness_initial_facts_exclude_positive_target_literal(tmp_path)


def test_method_validation_initial_facts_allocate_typed_witness_objects(tmp_path):
	pipeline_tests.assert_method_validation_initial_facts_allocate_typed_witness_objects(tmp_path)


def test_stage7_verifies_exported_hierarchical_plan_even_when_planner_available(
	tmp_path,
	monkeypatch,
):
	pipeline_tests.assert_stage7_verifies_exported_hierarchical_plan_even_when_planner_available(
		tmp_path,
		monkeypatch,
	)


def test_method_validation_initial_facts_ground_lowercase_schema_variables(tmp_path):
	pipeline_tests.assert_method_validation_initial_facts_ground_lowercase_schema_variables(tmp_path)
