from __future__ import annotations

import sys
from pathlib import Path

_src_dir = str(Path(__file__).parent.parent / "src")
if _src_dir not in sys.path:
	sys.path.insert(0, _src_dir)

from tests import test_pipeline as pipeline_tests

def test_stage3_summary_preserves_llm_timing_metadata(tmp_path, monkeypatch):
	pipeline_tests.assert_stage3_summary_preserves_llm_timing_metadata(tmp_path, monkeypatch)


def test_pipeline_requires_explicit_domain_file():
	pipeline_tests.assert_pipeline_requires_explicit_domain_file()


def test_seed_validation_scope_preserves_multi_type_object_assignments(tmp_path):
	pipeline_tests.assert_seed_validation_scope_preserves_multi_type_object_assignments(tmp_path)


def test_seed_validation_scope_accepts_parent_type_when_leaf_type_is_unconstrained(tmp_path):
	pipeline_tests.assert_seed_validation_scope_accepts_parent_type_when_leaf_type_is_unconstrained(
		tmp_path,
	)


def test_stage3_type_validation_fails_for_untyped_method_variable(tmp_path):
	pipeline_tests.assert_stage3_type_validation_fails_for_untyped_method_variable(tmp_path)


def test_problem_domain_name_mismatch_allows_compatible_problem(tmp_path):
	pipeline_tests.assert_problem_domain_name_mismatch_allows_compatible_problem(tmp_path)


def test_problem_domain_name_mismatch_rejects_incompatible_problem(tmp_path):
	pipeline_tests.assert_problem_domain_name_mismatch_rejects_incompatible_problem(tmp_path)


def test_method_task_argument_type_hints_prefer_explicit_task_args(tmp_path):
	pipeline_tests.assert_method_task_argument_type_hints_prefer_explicit_task_args(tmp_path)


def test_stage1_object_universe_merges_constants_from_atoms_and_formulas():
	pipeline_tests.assert_stage1_object_universe_merges_constants_from_atoms_and_formulas()


def test_ordered_literal_signatures_extracts_eventually_wrapped_atoms():
	pipeline_tests.assert_ordered_literal_signatures_extracts_eventually_wrapped_atoms()


def test_stage1_task_grounded_eventual_targets_drop_support_only_literals():
	pipeline_tests.assert_stage1_task_grounded_eventual_targets_drop_support_only_literals()


def test_stage1_task_grounded_singleton_support_targets_canonicalize_to_headline():
	pipeline_tests.assert_stage1_task_grounded_singleton_support_targets_canonicalize_to_headline()


def test_stage1_task_grounded_joint_eventual_bundle_canonicalizes_per_anchor():
	pipeline_tests.assert_stage1_task_grounded_joint_eventual_bundle_canonicalizes_per_anchor()


def test_stage1_task_grounded_satellite_headline_prefers_task_signature_match():
	pipeline_tests.assert_stage1_task_grounded_satellite_headline_prefers_task_signature_match()


def test_stage1_task_grounded_satellite_variable_arguments_use_typed_witness_grounding():
	pipeline_tests.assert_stage1_task_grounded_satellite_variable_arguments_use_typed_witness_grounding()


def test_ipc_plan_verifier_grounds_parameterised_root_tasks_from_trace():
	pipeline_tests.assert_ipc_plan_verifier_grounds_parameterised_root_tasks_from_trace()


def test_ipc_plan_verifier_reconstructs_multi_root_depth_first_method_traces():
	pipeline_tests.assert_ipc_plan_verifier_reconstructs_multi_root_depth_first_method_traces()


def test_official_blocksworld_problem_query_case_generation_from_problem_tasks():
	pipeline_tests.assert_official_blocksworld_problem_query_case_generation_from_problem_tasks()


def test_official_blocksworld_problem_query_case_generation_preserves_identical_root_task_occurrences():
	pipeline_tests.assert_official_blocksworld_problem_query_case_generation_preserves_identical_root_task_occurrences()


def test_official_marsrover_problem_query_case_generation_from_problem_tasks():
	pipeline_tests.assert_official_marsrover_problem_query_case_generation_from_problem_tasks()


def test_official_satellite_problem_query_case_generation_from_problem_tasks():
	pipeline_tests.assert_official_satellite_problem_query_case_generation_from_problem_tasks()


def test_query_task_anchor_extraction_uses_declared_tasks_only():
	pipeline_tests.assert_query_task_anchor_extraction_uses_declared_tasks_only()


def test_ordered_literal_signatures_preserve_identical_occurrences():
	pipeline_tests.assert_ordered_literal_signatures_preserve_identical_occurrences()


def test_task_grounded_canonical_formulas_preserve_identical_obligation_occurrences():
	pipeline_tests.assert_task_grounded_canonical_formulas_preserve_identical_obligation_occurrences()


def test_task_grounded_canonical_formulas_preserve_order_when_query_requests_sequence():
	pipeline_tests.assert_task_grounded_canonical_formulas_preserve_order_when_query_requests_sequence()


def test_task_grounded_stage1_normalisation_overrides_independent_eventuals_for_ordered_queries():
	pipeline_tests.assert_task_grounded_stage1_normalisation_overrides_independent_eventuals_for_ordered_queries()


def test_task_grounded_ordered_formulas_accumulate_prior_positive_obligations():
	pipeline_tests.assert_task_grounded_ordered_formulas_accumulate_prior_positive_obligations()


def test_ordered_literal_signatures_prefer_query_task_literal_contract():
	pipeline_tests.assert_ordered_literal_signatures_prefer_query_task_literal_contract()


def test_query_object_inventory_extraction_preserves_full_benchmark_inventory():
	pipeline_tests.assert_query_object_inventory_extraction_preserves_full_benchmark_inventory()


def test_expected_execution_identity_is_derived_from_selected_domain_and_problem():
	pipeline_tests.assert_expected_execution_identity_is_derived_from_selected_domain_and_problem()


def test_stage1_generation_uses_only_instruction_even_with_problem_file(monkeypatch):
	pipeline_tests.assert_stage1_generation_uses_only_instruction_even_with_problem_file(monkeypatch)


def test_stage6_object_type_resolution_ignores_unused_query_objects():
	pipeline_tests.assert_stage6_object_type_resolution_ignores_unused_query_objects()


def test_stage3_uses_query_inventory_for_grounding_even_when_semantic_objects_are_partial(
	tmp_path,
	monkeypatch,
):
	pipeline_tests.assert_stage3_uses_query_inventory_for_grounding_even_when_semantic_objects_are_partial(
		tmp_path,
		monkeypatch,
	)


def test_stage6_problem_seed_facts_ignore_stage4_witness_facts():
	pipeline_tests.assert_stage6_problem_seed_facts_ignore_stage4_witness_facts()


def test_method_validation_initial_facts_are_branch_specific(tmp_path):
	pipeline_tests.assert_method_validation_initial_facts_are_branch_specific(tmp_path)


def test_method_validation_initial_facts_avoid_conflicting_global_defaults(tmp_path):
	pipeline_tests.assert_method_validation_initial_facts_avoid_conflicting_global_defaults(tmp_path)


def test_task_witness_initial_facts_merge_sibling_branches(tmp_path):
	pipeline_tests.assert_task_witness_initial_facts_merge_sibling_branches(tmp_path)


def test_transition_witness_initial_facts_exclude_positive_target_literal(tmp_path):
	pipeline_tests.assert_transition_witness_initial_facts_exclude_positive_target_literal(tmp_path)


def test_method_validation_initial_facts_allocate_typed_witness_objects(tmp_path):
	pipeline_tests.assert_method_validation_initial_facts_allocate_typed_witness_objects(tmp_path)


def test_stage7_verifies_exported_hierarchical_plan_even_when_planner_available(
	tmp_path,
	monkeypatch,
):
	pipeline_tests.assert_stage7_verifies_exported_hierarchical_plan_even_when_planner_available(
		tmp_path,
		monkeypatch,
	)


def test_method_validation_initial_facts_ground_lowercase_schema_variables(tmp_path):
	pipeline_tests.assert_method_validation_initial_facts_ground_lowercase_schema_variables(tmp_path)
