(define (problem blocksworld-minimal)
  (:domain blocksworld-4ops)
  (:objects a b c - block)
  (:init
    (on a b)
    (on b c)
    (ontable c)
    (clear a)
    (handempty))
  (:goal (not (on a b)))
)
